meta:
  language: ru
language_menu:
#   -
#       name: ru
#       description: по-русски
#       type: node
#       url: /ru
   -
       name: en
       description: in english
       type: node
       css_class: navbar-right
       url: /
menu:
   -
       name: думаю
       description: Мысли обо всём
       css_class: blog
       type: node
       url: /ru/blog/
   -
       name: читаю
       description: книги, которые я читаю
       type: node
       url: /ru/books/
   -
       name: путешествую
       description: места, где я побывал
       type: node
       url: /ru/travel/
#   -
#       name: Blog
#       description: Blog
#       css_class: blog
#       type: node
#       url: blog
#   -
#       name: About
#       description: About
#       css_class: about
#       type: page
#       url: about.html
